[transition=none,%notitle]
== Queries

--
[English,step=1]
Original question
[English,step=1]
[source, console]
---- "Hey Wikidata, Which organisms are known to contain quercetin (REFJWTPEDVJJIY-UHFFFAOYSA-N)?" ----
--

--
[SPARQL,step=2]
SPARQL translation
[SPARQL,step=2]
[source, sql]
---- SELECT DISTINCT ?parent_taxon ?parent_taxonname ?taxon ?taxonname WHERE {
VALUES ?classes { wd:Q11173 wd:Q59199015 } ?compound wdt:P31 ?classes; wdt:P235 "REFJWTPEDVJJIY-UHFFFAOYSA-N".
?taxon wdt:P171 ?parent_taxon. { ?compound p:P703 ?stmt.
?stmt ps:P703 ?taxon. { ?stmt prov:wasDerivedFrom ?ref.
?ref pr:P248 ?art. ?art wdt:P356 ?art_doi.
} } ?taxon wdt:P225 ?taxonname.
?parent_taxon wdt:P225 ?parent_taxonname.} ----
--

[result,step=3]
👉 https://w.wiki/36a2

=== Organisms containing quercetin

[.stretch]
++++
<iframe src="https://query.wikidata.org/embed.html#SELECT%20DISTINCT%20%3Fparent_taxon%20%3Fparent_taxonname%20%3Ftaxon%20%3Ftaxonname%20WHERE%20%7B%0A%20%20VALUES%20%3Fclasses%20%7B%0A%20%20%20%20wd%3AQ11173%0A%20%20%20%20wd%3AQ59199015%0A%20%20%7D%0A%20%20%3Fcompound%20wdt%3AP31%20%3Fclasses%3B%0A%20%20%20%20wdt%3AP235%20%22REFJWTPEDVJJIY-UHFFFAOYSA-N%22.%0A%20%20%3Ftaxon%20wdt%3AP171%20%3Fparent_taxon.%0A%20%20%7B%0A%20%20%20%20%3Fcompound%20p%3AP703%20%3Fstmt.%0A%20%20%20%20%3Fstmt%20ps%3AP703%20%3Ftaxon.%0A%20%20%20%20%7B%0A%20%20%20%20%20%20%3Fstmt%20prov%3AwasDerivedFrom%20%3Fref.%0A%20%20%20%20%20%20%3Fref%20pr%3AP248%20%3Fart.%0A%20%20%20%20%20%20%3Fart%20wdt%3AP356%20%3Fart_doi.%0A%20%20%20%20%7D%0A%20%20%7D%0A%20%20%3Ftaxon%20wdt%3AP225%20%3Ftaxonname.%0A%20%20%3Fparent_taxon%20wdt%3AP225%20%3Fparent_taxonname.%0A%7D" referrerpolicy="origin" sandbox="allow-scripts allow-same-origin allow-popups" width="1200px" height="500px title="Query 1""></iframe>
++++

=== Structures found in _Quercus_ spp.

👉 https://w.wiki/36Zk

[.stretch]
++++
<iframe src="https://query.wikidata.org/embed.html#SELECT%20DISTINCT%20%3FtaxonLabel%20%3FcompoundLabel%20WHERE%20%7B%0A%20%20VALUES%20%3Fclasses%20%7B%0A%20%20%20%20wd%3AQ11173%0A%20%20%20%20wd%3AQ59199015%0A%20%20%7D%0A%20%20%3Fcompound%20wdt%3AP31%20%3Fclasses.%0A%20%20%3Ftaxon%20wdt%3AP171%20%3Fparent_taxon.%0A%20%20%3Fparent_taxon%20wdt%3AP225%20%22Quercus%22.%0A%20%20%7B%0A%20%20%20%20%3Fcompound%20p%3AP703%20%3Fstmt.%0A%20%20%20%20%3Fstmt%20ps%3AP703%20%3Ftaxon%3B%0A%20%20%20%20%20%20prov%3AwasDerivedFrom%20%3Fref.%0A%20%20%20%20%3Fref%20pr%3AP248%20%3Fart.%0A%20%20%20%20%3Fart%20wdt%3AP356%20%3Fart_doi.%0A%20%20%7D%0A%20%20SERVICE%20wikibase%3Alabel%20%7B%20bd%3AserviceParam%20wikibase%3Alanguage%20%22en%22.%20%7D%0A%7D" referrerpolicy="origin" sandbox="allow-scripts allow-same-origin allow-popups" width="1200px" height="500px" title="Query 2"/></iframe>
++++

=== Structures with anti-infective activity per genus

👉 https://w.wiki/vnU

[.stretch]
++++
<iframe src="https://query.wikidata.org/embed.html#%23%20Compounds%20that%20have%20%0A%23%20%281%29%20an%20InChiKey%0A%23%20%282%29%20a%20%22found%20in%20taxon%22%20statement%20with%20a%20reference%20that%20has%20a%20DOI%20and%20a%20title%0A%23%20%283%29%20are%20considered%20as%20%22anti-infective%20agent%22%0ASELECT%20DISTINCT%20%3Fparent_taxon%20%3Fparent_taxon_name%20%28COUNT%28%3Fcompound%29%20AS%20%3Fcount%29%20WHERE%20%7B%0A%20%20%3Fcompound%20wdt%3AP2868%20%3Fmesh.%0A%20%20%3Fmesh%20wdt%3AP486%20%22D000890%22.%0A%20%20%3Fcompound%20wdt%3AP235%20%3Finchikey.%0A%20%20%7B%0A%20%20%20%20%3Fcompound%20p%3AP703%20%3Fstatement.%0A%20%20%20%20%3Fstatement%20ps%3AP703%20%3Ftaxon.%0A%20%20%20%20%3Ftaxon%20wdt%3AP171%20%3Fparent_taxon.%0A%20%20%20%20OPTIONAL%20%7B%20%3Ftaxon%20wdt%3AP171%20%3Fparent_taxon.%20%7D%0A%20%20%20%20OPTIONAL%20%7B%20%3Fparent_taxon%20wdt%3AP225%20%3Fparent_taxon_name.%20%7D%0A%20%20%20%20%7B%0A%20%20%20%20%20%20%3Fstatement%20prov%3AwasDerivedFrom%20%3Fref.%0A%20%20%20%20%20%20%3Fref%20pr%3AP248%20%3Freference.%0A%20%20%20%20%20%20%3Freference%20wdt%3AP356%20%3Freference_doi%3B%0A%20%20%20%20%20%20%20%20wdt%3AP1476%20%3Freference_title.%0A%20%20%20%20%7D%0A%20%20%7D%0A%20%20SERVICE%20wikibase%3Alabel%20%7B%20bd%3AserviceParam%20wikibase%3Alanguage%20%22%5BAUTO_LANGUAGE%5D%2Cen%22.%20%7D%0A%7D%0AGROUP%20BY%20%3Fparent_taxon%20%3Fparent_taxon_name%0AORDER%20BY%20DESC%20%28%3Fcount%29" referrerpolicy="origin" sandbox="allow-scripts allow-same-origin allow-popups" width="1200px" height="500px" title="Query 4"/></iframe>
++++
